version = 1

exclude_patterns = [
  "/public",
  "/templates"
]

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "rust"
enabled = true

  [analyzers.meta]
  msrv = "1.50.0"

[[transformers]]
name = "rustfmt"
enabled = true

[[transformers]]
name = "prettier"
enabled = true