[package]
name = "wlrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket", version = "0.5.0-rc.1", features = ["json"] }
rocket_db_pools = { git = "https://github.com/SergioBenitez/Rocket", version = "0.1.0-rc", features = ["sqlx_sqlite"] }
rocket_dyn_templates = { git = "https://github.com/SergioBenitez/Rocket", version = "0.1.0-rc.1", features = ["handlebars"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = { version = "1.0.68" }
sqlx = { version = "0.5", features = ["macros", "migrate", "sqlite"], default-features = false }
lazy_static = "1.4.0"
ordered-float = { version = "3.0", default-features = false, features = ["serde", "std"] }
tokio = "1.18.1"
tokio-test = "0.4.2"
time = { version = "0.3.9", features = ["std", "serde", "serde-human-readable"] }
log = "0.4.0"
env_logger = "0.9"
uuid = { version = "1.0.0", features = ["v4", "fast-rng"] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = 3