[package]
name = "wlrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket"}
#skytable = { version = "0.7.0", features = ["aio", "const-gen"], default-features = false }
serde_json = "1.0.68"
serde = { version = "1.0.130", features = ["derive"] }
sqlx = { version = "0.5", features = ["macros", "migrate", "sqlite"], default-features = false }
rocket_db_pools = { git = "https://github.com/SergioBenitez/Rocket", version = "0.1.0-rc", features = ["sqlx_sqlite"] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = 3