[package]
name = "wlrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket"}
serde_json = { version = "1.0.68" }
serde = { version = "1.0.137", features = ["derive"] }
sqlx = { version = "0.5", features = ["macros", "migrate", "sqlite"], default-features = false }
rocket_db_pools = { git = "https://github.com/SergioBenitez/Rocket", version = "0.1.0-rc", features = ["sqlx_sqlite"] }
lazy_static = "1.4.0"
ordered-float = { version = "3.0", default-features = false, features = ["serde", "std"] }
tokio = "1.18.1"
tokio-test = "0.4.2"

[dependencies.uuid]
version = "1.0.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = 3