[package]
name = "wlrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.5.1", features = ["headers"] }
askama = "0.11.1"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = 3