[default.databases.sqlite_db]
url = "sqlite://data.db"

min_connections = 8
max_connections = 1024
connect_timeout = 5
idle_timeout = 120

[default]
template_dir = "templates"
address = "0.0.0.0"
port = 8000
# Note, change to env variable which is set in docker-compose.yml
secret_key = "qZOir1b8GaaRDTqNX18fTqqub3T4ChR/aWnzZU2QP1s="

[global.compress]
exclude = ["text/html", "image/avif", "image/png", "image/jpeg", "image/gif"]