[default.databases.sqlite_db]
url = "sqlite://data.db"

min_connections = 8
max_connections = 1024
connect_timeout = 5
idle_timeout = 120

[default]
template_dir = "templates"
address = "127.0.0.1"
port = 8000